### ISSUE TITLE
Launching run_simScript with debug leads to crash

### ISSUE THREAD

**Issue by antonioiuliano2** [ShipSoft/FairShip#299]
Dear all,

I cannot do overlap and field checks with the master FairShip version anymore.
When setting debug=2 in run_simScript.py, a simulation crash with the following message:

Vol is TimeDet
will not search in  ['DecayVolume', 'Tr1', 'Tr2', 'Tr3', 'Tr4', 'Veto', 'Ecal', 'Hcal', 'MuonDetector', 'SplitCal']
MuonShieldArea/MagnAbsorb2_MiddleMagL 1 volume =  7.00m3  mass = 55.10 t
++++  TG4Warning:  ++++
    TG4GeometryServices::FindLogicalVolume:
    Logical volume { 'M', 'a', 'g', 'n', 'A', 'b', 's', 'o', 'r', 'b', '2', '_', 'M', 'i', 'd', 'd', 'l', 'e', 'M', 'a', 'g', 'L' } not found.
+++++++++++++++++++++++

 *** Break *** segmentation violation

It seems to complain for a missing volume, but I do not know which volume is talking about.
Best regards,
Antonio Iuliano

P.S. tested with 2020 version (a.k.a. master)

**Comment by ThomasRuf** [comment]
comment the lines:
 geomGeant4.printVMCFields()
 geomGeant4.printWeightsandFields(onlyWithField = True,\
             exclude=['DecayVolume','Tr1','Tr2','Tr3','Tr4','Veto','Ecal','Hcal','MuonDetector','SplitCal'])

will debug later. Overlap checking itself works.

**Comment by antonioiuliano2** [comment]
Thank you for your reply.

**Comment by ThomasRuf** [comment]
what does not work anymore is the following line:
name = ROOT.G4String(lvl.GetName().__str__()) 

instead of returning a string, it returns a list of characters:
 'M', 'a', 'g', 'n', 'A', 'b', 's', 'o', 'r', 'b', '2', '_', 'M', 'i', 'd', 'd', 'l', 'e', 'M', 'a', 'g', 'L' } 
MagnAbsorber2_MiddleMagL

must be related with the transition to python3. don't know how to fix it for the moment. Anybody any idea?

**Comment by ThomasRuf** [comment]
I think I fixed it. Commit 91d2118d2ff8c8aa62234545c2f53ce3205e821f
