### ISSUE TITLE
Issue with SST parameters

### ISSUE THREAD

**Issue by anupama-reghunath** [ShipSoft/FairShip#489]
With the new parameters for the SST, I'm having trouble running simulations. DeltazPlane and YPlaneOffset are now missing in geometry_config.py, but are used in the shipDet_conf.py and subsequently in strawtubes.cxx,
For the timebeing and also for backward compatibility, I've set them as
```
     c.strawtubes.DeltazPlane  = 0*u.cm
     c.strawtubes.YPlaneOffset = 0*u.cm
```
but not sure if the implementation is accurate.
Also, stereoangle expected is an integer in the .cxx and the respective header, and not a float value(4.57). 

Tested after these changes, seems to be working.

**Comment by olantwin** [comment]
CC @ukmartylee

**Comment by ukmartylee** [comment]
Setting them to zero at the moment, I think, would be fine. My concern is that by the definition in strawtubes.cxx, would the fact that two planes are created and placed at the same position (overlapping each other) be an issue? Otherwise, we’ll have to remove the plane loop in strawtubes.cxx completely.

And it would be sufficient for the stereo angle to just be 5, since this value is not fixed at the moment.

**Comment by olantwin** [comment]
Overlaps should be avoided. Removing the plane loop sounds like the best solution.

We should probably allow for non-integer angles, should be a very simple change.

**Comment by ukmartylee** [comment]
The interim solution could be that we’ll just perform 1 plane loop. Meanwhile, I’ll try to remove all plane-related variables and codes.

**Comment by olantwin** [comment]
Thanks a lot!

Could you please implement this interim solution, so that the simulation and reconstruction work again?
