### ISSUE TITLE
EvtCalc: add more LLP models

### ISSUE THREAD

**Issue by mferril** [ShipSoft/FairShip#536]
To be included in the main pythonic EventCalc implementation.

Assignee: @maksymovchynnikov

**Comment by olantwin** [comment]
Thanks @maksymovchynnikov, could you please tag a release? It would be nice, if we could also add a recipe of how to install EventCalc to https://github.com/ShipSoft/shipdist, so that the new features can be used by everyone.

I would also recommend renaming the repo and maybe making an EventCalc organisation for it (or you are welcome to move it to the SHiP organisation, but I'd assume you want this to be developed independently of SHiP?)
